### ISSUE TITLE
When forget to input ae token amount in step6

### ISSUE THREAD

**Issue by 2pd** [aeternity/aepp-token-migration#108]
There is no warning information if user don't type ae token amount. This is useful only when you want to do a testing or verifying the process. But I would suggest to give a highlight message before starting to migrate.

Actually there are some migrate transactions with 0 ae tokens.  Like this

https://etherscan.io/tx/0x6c2452a620f94b26402b951ad2fd7b4a9194a8106582a01701103cad77b5b885

and more

**Comment by sadiqevani** [comment]
Hello @2pd,

We're working on this fix! We already have implemented a blocking action for MyEtherWallet.

Thank you a lot for your input.
